---
- name: Desplegar una aplicaci贸n web simple
  hosts: all
  become: yes
  tasks:
    - name: Instalar dependencias
      apt:
        name:
          - git
          - python3-pip
        state: present

    - name: Clonar el repositorio de la aplicaci贸n
      git:
        repo: 'https://github.com/tu_usuario/tu_repositorio.git'
        dest: /opt/mi_app

    - name: Instalar dependencias de la aplicaci贸n
      pip:
        requirements: /opt/mi_app/requirements.txt

    - name: Ejecutar la aplicaci贸n
      shell: |
        cd /opt/mi_app
        nohup python3 app.py &
